export BASH_CONF="bashrc"
export LC_ALL=en_US.UTF-8

export MUSHROOMBASE=~/workspace/kkchuchu.mushroom
export PATH=$PATH:${MUSHROOMBASE}/bin/

export GITAWAREPROMPT=${MUSHROOMBASE}/bin/git-aware-prompt
source "${GITAWAREPROMPT}/main.sh"
export PS1="\u@\h \W \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
